# Generated by Django 4.0 on 2021-12-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('pub_date', models.DateField()),
                ('rating', models.FloatField(default=0)),
                ('genres', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
